run:
  deadline: 10m

linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  disable:
    - typecheck

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/k8s-device-plugin
  gosec:
    excludes:
      - G404
