{{- if eq (include "nvidia-device-plugin.hasConfigFiles" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvidia-device-plugin.fullname" . }}-configs
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
data:
{{- range $name, $contents := $.Values.config }}
  {{ $name }}: |-
{{ $contents | indent 4 }}
{{- end -}}
{{- end -}}
