# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.gfd.enabled }}

{{- $root := . }}
{{- $hasConfigFiles := (include "nvidia-device-plugin.hasConfigFiles" .) | trim }}
{{- $defaultConfig := (include "nvidia-device-plugin.getDefaultConfig" .) | trim }}
{{- $migStrategiesAreAllNone := (include "nvidia-device-plugin.allPossibleMigStrategiesAreNone" .) | trim }}

{{- with .Subcharts.gfd }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nvidia-device-plugin.fullname" . }}
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nvidia-device-plugin.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "nvidia-device-plugin.templateLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      priorityClassName: "system-node-critical"
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq $hasConfigFiles "true" }}
      serviceAccountName: {{ include "nvidia-device-plugin.fullname" $root }}-service-account
      shareProcessNamespace: true
      initContainers:
      - image: {{ include "nvidia-device-plugin.fullimage" $root }}
        name: gpu-feature-discovery-init
        command: ["config-manager"]
        env:
        - name: ONESHOT
          value: "true"
        - name: KUBECONFIG
          value: ""
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: "spec.nodeName"
        - name: NODE_LABEL
          value: "nvidia.com/device-plugin.config"
        - name: CONFIG_FILE_SRCDIR
          value: "/available-configs"
        - name: CONFIG_FILE_DST
          value: "/config/config.yaml"
        - name: DEFAULT_CONFIG
          value: "{{ $defaultConfig }}"
        - name: SEND_SIGNAL
          value: "false"
        - name: SIGNAL
          value: ""
        - name: PROCESS_TO_SIGNAL
          value: ""
        volumeMounts:
          - name: available-configs
            mountPath: /available-configs
          - name: config
            mountPath: /config
      {{- end }}
      containers:
      {{- if eq $hasConfigFiles "true" }}
        - image: {{ include "nvidia-device-plugin.fullimage" $root }}
          name: gpu-feature-discovery-sidecar
          command: ["config-manager"]
          env:
          - name: ONESHOT
            value: "false"
          - name: KUBECONFIG
            value: ""
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: "spec.nodeName"
          - name: NODE_LABEL
            value: "nvidia.com/device-plugin.config"
          - name: CONFIG_FILE_SRCDIR
            value: "/available-configs"
          - name: CONFIG_FILE_DST
            value: "/config/config.yaml"
          - name: DEFAULT_CONFIG
            value: "{{ $defaultConfig }}"
          - name: SEND_SIGNAL
            value: "false"
          - name: SIGNAL
            value: ""
          - name: PROCESS_TO_SIGNAL
            value: ""
          volumeMounts:
            - name: available-configs
              mountPath: /available-configs
            - name: config
              mountPath: /config
      {{- end }}
        - image: {{ include "nvidia-device-plugin.fullimage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: gpu-feature-discovery-ctr
          env:
          {{- if typeIs "bool" .Values.failOnInitError }}
            - name: GFD_FAIL_ON_INIT_ERROR
              value: "{{ .Values.failOnInitError }}"
          {{- end }}
          {{- if typeIs "string" .Values.migStrategy }}
            - name: GFD_MIG_STRATEGY
              value: "{{ .Values.migStrategy }}"
          {{- end }}
          {{- if typeIs "bool" .Values.noTimestamp }}
            - name: GFD_NO_TIMESTAMP
              value: "{{ .Values.noTimestamp}}"
          {{- end }}
          {{- if or (typeIs "string" .Values.sleepInterval) (typeIs "int" .Values.sleepInterval) }}
            - name: GFD_SLEEP_INTERVAL
              value: "{{ .Values.sleepInterval }}"
          {{- end }}
          {{- if eq $hasConfigFiles "true" }}
            - name: GFD_CONFIG_FILE
              value: /config/config.yaml
          {{- end }}
          {{- if ne $migStrategiesAreAllNone "true" }}
            - name: NVIDIA_MIG_MONITOR_DEVICES
              value: all
          {{- end }}
          securityContext:
          {{- if ne (len .Values.securityContext) 0 }}
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- else if ne $migStrategiesAreAllNone "true" }}
              capabilities:
                add:
                  - SYS_ADMIN
          {{- else }}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          {{- end }}
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-product-name
              mountPath: "/sys/class/dmi/id/product_name"
          {{- if eq $hasConfigFiles "true" }}
            - name: available-configs
              mountPath: /available-configs
            - name: config
              mountPath: /config
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
      {{- if eq $hasConfigFiles "true" }}
        - name: available-configs
          configMap:
            name: {{ include "nvidia-device-plugin.fullname" $root }}-configs
        - name: config
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- end }}
