{{- if eq (include "nvidia-device-plugin.hasConfigFiles" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-device-plugin.fullname" . }}-service-account
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nvidia-device-plugin.labels" . | nindent 4 }}
{{- end }}
